# TODO: MODIFY ME BEFORE USE!
runtime: python312

env_variables:
  DESTINATION: "<10.128.0.2:80>"


vpc_access_connector:
  name: projects/dulcet-buttress-484713-m8/locations/us-central1/connectors/testconnector
  egress_setting: private-ranges-only
