# TODO: MODIFY ME BEFORE USE!
runtime: python312

env_variables:
  DESTINATION: "<10.128.0.2:80>"


vpc_access_connector:
  name: projects/qwiklabs-gcp-00-542b577b7439/locations/us-central1/connectors/testconnector
  egress_setting: private-ranges-only
